export enum DiscipleSearchType {
  FirstName = 'first_name',
  LastName = 'last_name',
  FullName = 'full_name',
  BirthDate = 'birth_date', 
  BirthMonth = 'birth_month', 
  Gender = 'gender',
  MaritalStatus = 'marital_status',
  OriginCountry = 'origin_country' ,
  ZoneName = 'zone_name',
  FamilyGroupCode = 'family_group_code',
  FamilyGroupName = 'family_group_name',
  Department = 'department',
  Province = 'province',
  District = 'district',
  UrbanSector = 'urban_sector',
  Address = 'address',
  RecordStatus = 'record_status',
}

export const DiscipleSearchTypeNames: Record<DiscipleSearchType, string> =  {
  [DiscipleSearchType.FirstName]: 'Nombres',
  [DiscipleSearchType.LastName]: 'Apellidos',
  [DiscipleSearchType.FullName]: 'Nombres y Apellidos',
  [DiscipleSearchType.BirthDate]: 'Fecha de nacimiento',
  [DiscipleSearchType.BirthMonth]: 'Mes de nacimiento',
  [DiscipleSearchType.Gender]: 'Género',
  [DiscipleSearchType.MaritalStatus]: 'Estado civil',
  [DiscipleSearchType.OriginCountry]: 'País de origen',
  [DiscipleSearchType.ZoneName]: 'Nombre de Zona',
  [DiscipleSearchType.FamilyGroupCode]: 'Código de grupo familiar',
  [DiscipleSearchType.FamilyGroupName]: 'Nombre de grupo familiar',
  [DiscipleSearchType.Department]: 'Departamento',
  [DiscipleSearchType.Province]: 'Provincia',
  [DiscipleSearchType.District]: 'Distrito',
  [DiscipleSearchType.UrbanSector]: 'Sector Urbano',
  [DiscipleSearchType.Address]: 'Dirección',
  [DiscipleSearchType.RecordStatus]: 'Estado de registro',
}
