
export enum FieldName {
  firstName = 'firstName',
  lastName = 'lastName',
  gender = 'gender',
  originCountry = 'originCountry',
  maritalStatus = 'maritalStatus',
  dateBirth = 'dateBirth',
  numberChildren = 'numberChildren',
  conversionDate = 'conversionDate',
  emailAddress = 'emailAddress',
  phoneNumber = 'phoneNumber',
  country = 'country',
  department = 'department',
  province = 'province',
  district = 'district',
  address = 'address',
  roles = 'roles',
  theirPastor = 'theirPastor',
  theirCopastor = 'theirCopastor',
  theirSupervisor = 'theirSupervisor',
  theirFamilyHouse = 'theirFamilyHouse',
  isActive = 'isActive',
}