export enum PreacherFieldNames {
  FirstNames = 'firstNames',
  LastNames = 'lastNames',
  Gender = 'gender',
  OriginCountry = 'originCountry',
  BirthDate = 'birthDate',
  MaritalStatus = 'maritalStatus',
  NumberChildren = 'numberChildren',
  ConversionDate = 'conversionDate',
  Email = 'email',
  PhoneNumber = 'phoneNumber',
  ResidenceCountry = 'residenceCountry',
  ResidenceDepartment = 'residenceDepartment',
  ResidenceProvince = 'residenceProvince',
  ResidenceDistrict = 'residenceDistrict',
  ResidenceUrbanSector = 'residenceUrbanSector',
  ResidenceAddress = 'residenceAddress',
  ReferenceAddress = 'referenceAddress',
  Roles = 'roles',
  RecordStatus = 'recordStatus',
  IsDirectRelationToPastor = 'isDirectRelationToPastor',
  TheirSupervisor = 'theirSupervisor',
}
