export enum PreacherSearchType {
  FirstName = 'first_name',
  LastName = 'last_name',
  FullName = 'full_name',
  BirthDate = 'birth_date', 
  BirthMonth = 'birth_month', 
  Gender = 'gender',
  MaritalStatus = 'marital_status',
  OriginCountry = 'origin_country' ,
  ZoneName = 'zone_name',
  ZoneId = 'zone_id',
  FamilyGroupCode = 'family_group_code',
  FamilyGroupName = 'family_group_name',
  Department = 'department',
  Province = 'province',
  District = 'district',
  UrbanSector = 'urban_sector',
  Address = 'address',
  RecordStatus = 'record_status',
}

export const PreacherSearchTypeNames: Partial<Record<PreacherSearchType, string>> =  {
  [PreacherSearchType.FirstName]: 'Nombres',
  [PreacherSearchType.LastName]: 'Apellidos',
  [PreacherSearchType.FullName]: 'Nombres y Apellidos',
  [PreacherSearchType.BirthDate]: 'Fecha de nacimiento',
  [PreacherSearchType.BirthMonth]: 'Mes de nacimiento',
  [PreacherSearchType.Gender]: 'Género',
  [PreacherSearchType.MaritalStatus]: 'Estado civil',
  [PreacherSearchType.OriginCountry]: 'País de origen',
  [PreacherSearchType.ZoneName]: 'Nombre de Zona',
  [PreacherSearchType.FamilyGroupCode]: 'Código de grupo familiar',
  [PreacherSearchType.FamilyGroupName]: 'Nombre de grupo familiar',
  [PreacherSearchType.Department]: 'Departamento',
  [PreacherSearchType.Province]: 'Provincia',
  [PreacherSearchType.District]: 'Distrito',
  [PreacherSearchType.UrbanSector]: 'Sector Urbano',
  [PreacherSearchType.Address]: 'Dirección',
  [PreacherSearchType.RecordStatus]: 'Estado de registro',
}

