
export enum FieldName {
  FirstName = 'firstName',
  LastName = 'lastName',
  Gender = 'gender',
  OriginCountry = 'originCountry',
  MaritalStatus = 'maritalStatus',
  DateBirth = 'dateBirth',
  NumberChildren = 'numberChildren',
  ConversionDate = 'conversionDate',
  EmailAddress = 'emailAddress',
  PhoneNumber = 'phoneNumber',
  Country = 'country',
  Department = 'department',
  Province = 'province',
  District = 'district',
  Address = 'address',
  Roles = 'roles',
  TheirPastor = 'theirPastor',
  TheirCopastor = 'theirCopastor',
  TheirSupervisor = 'theirSupervisor',
  TheirFamilyHouse = 'theirFamilyHouse',
  // IsActive = 'isActive',
}

