export enum FieldNames {
  FirstName = 'firstName',
  LastName = 'lastName',
  Gender = 'gender',
  OriginCountry = 'originCountry',
  BirthDate = 'birthDate',
  MaritalStatus = 'maritalStatus',
  NumberChildren = 'numberChildren',
  ConversionDate = 'conversionDate',
  Email = 'email',
  PhoneNumber = 'phoneNumber',
  Country = 'country',
  Department = 'department',
  Province = 'province',
  District = 'district',
  UrbanSector = 'urbanSector',
  Address = 'address',
  ReferenceAddress = 'referenceAddress',
  Roles = 'roles',
  Status = 'status',
  // TheirPastor = 'theirPastor',
  // TheirCopastor = 'theirCopastor',
  // TheirSupervisor = 'theirSupervisor',
  TheirChurch = 'theirFamilyHouse',
}
